sudo: required
services:
  - docker

before_install:
  - docker build -t mitsuru53/react-test -f ./client/Dockerfile.dev .

script:
  - docker run mitsuru53/react-test npm test -- --coverage

after_success:
  - docker build -t mitsuru53/multi-client ./client
  - docker build -t mitsuru53/multi-nginx ./nginx
  - docker build -t mitsuru53/multi-server ./server
  - docker build -t mitsuru53/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push misturu53/multi-client
  - docker push misturu53/multi-nginx
  - docker push misturu53/multi-server
  - docker push misturu53/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: serverless-app-wai-photos
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
